baseurl = "https://jennprk.github.io/GitBlog/"
languageCode = "en-us"
title = "Ji-Eun Park"
theme = "minimal"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"
enableEmoji = true
canonifyurls = true
hasCJKLanguage = true

[params]
    author = "Ji-Eun Park"
    description = "New York, NY   |   Biostatistics Research Assistant at Weill Cornell Medicine"
    githubUsername = "ji-eun-park"
    accent = "#00462a"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "R", "python"]
    favicon = ""

[[menu.main]]
    url = "https://jennprk.github.io/GitBlog/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "https://jennprk.github.io/GitBlog/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "https://jennprk.github.io/GitBlog/class/"
    name = "Projects"
    weight = 3


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:jip2008@med.cornell.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jennprk/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.facebook.com/jieunprk"
    name = "facebook-f"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/ji-eun-park/"
    name = "linkedin"
    weight = 4
